FROM mathworks/matlab-deps:R2025a

RUN apt-get update && apt-get upgrade -y && apt-get install wget -y

ENV EXTRACTEDDIR="/opt/matlabruntime/unzippedinstaller"

RUN mkdir -p $EXTRACTEDDIR 

# Write the installer file
RUN touch $EXTRACTEDDIR/installInputs.txt
RUN printf "destinationFolder=/opt/matlabruntime\n" > $EXTRACTEDDIR/installInputs.txt
RUN printf "agreeToLicense=yes\n" > $EXTRACTEDDIR/installInputs.txt
RUN printf "product.MATLAB Base Runtime\n" >> $EXTRACTEDDIR/installInputs.txt
RUN printf "product.MATLAB Production Server Runtime Addon\n" >> $EXTRACTEDDIR/installInputs.txt

RUN wget -q https://ssd.mathworks.com/supportfiles/downloads/R2025a/Release/1/deployment_files/installer/complete/glnxa64/MATLAB_Runtime_R2025a_Update_1_glnxa64.zip && \
    unzip -q MATLAB_Runtime_R2025a_Update_1_glnxa64.zip -d $EXTRACTEDDIR && \
    rm MATLAB_Runtime_R2025a_Update_1_glnxa64.zip && $EXTRACTEDDIR/install -bat true -inputFile $EXTRACTEDDIR/installInputs.txt && \
    rm -rf $EXTRACTEDDIR

RUN unlink /opt/matlabruntime/R2025a/sys/os/glnxa64/libstdc++.so.6
RUN ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /opt/matlabruntime/R2025a/sys/os/glnxa64/libstdc++.so.6

ENV TZ="Etc/UTC"

ENV LD_LIBRARY_PATH="/opt/matlabruntime/R2025a/runtime/glnxa64:/opt/matlabruntime/R2025a/bin/glnxa64:/opt/matlabruntime/R2025a/sys/os/glnxa64:/opt/matlabruntime/R2025a/sys/opengl/lib/glnxa64:/opt/matlabruntime/R2025a/extern/bin/glnxa64"

RUN apt-get update && apt-get upgrade -y

COPY matlabBackEndService/applicationFilesForMATLABCompiler /usr/bin/mlrtapp
RUN chmod -R a+rX /usr/bin/mlrtapp/*

RUN if ["$(getent passwd appuser | cut -d: -f1)" = ""] ; then useradd -ms /bin/bash appuser ; fi
USER appuser

ENTRYPOINT ["/opt/matlabruntime/R2025a/bin/glnxa64/muserve", "-a", "/usr/bin/mlrtapp/mymagic.ctf"]